{
  "swagger": "2.0",
  "info": {
    "version": "1.0.0",
    "title": "Financial Accounting",
    "description": "Handles financial booking of all business activity in a ledger/sub-ledger accounting structure"
  },
  "host": "bianorg.azure-api.net",
  "basePath": "/financial-accounting/v1",
  "securityDefinitions": {
    "apiKeyHeader": {
      "type": "apiKey",
      "name": "Ocp-Apim-Subscription-Key",
      "in": "header"
    }
  },
  "security": [
    {
      "apiKeyHeader": []
    }
  ],
  "schemes": [
    "https"
  ],
  "paths": {
    "/financial-accounting/financial-booking-log": {
      "get": {
        "tags": [
          "retrieve"
        ],
        "summary": "Retrieve all available Financial Accounting Control Record Ids",
        "operationId": "retrieveFinancialAccountingRefernceIds",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "collection-filter",
            "in": "query",
            "description": "Filter to refine the result set. ex- 'base-currency = USD'",
            "required": false,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "successfully retrieved Financial Accounting Control Record Ids",
            "schema": {
              "type": "array",
              "items": {
                "type": "string"
              },
              "example": [
                "FA123",
                "FA345"
              ]
            }
          }
        }
      }
    },
    "/financial-accounting/financial-booking-log/behavior-qualifiers": {
      "get": {
        "tags": [
          "retrieve"
        ],
        "summary": "Retrieve all Behaviour Qualifier names for Financial Accounting",
        "operationId": "retrieveFinancialAccountingBQsProcedure",
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successfully retrieved Financial Accounting Behavior Qualifier Names",
            "schema": {
              "type": "array",
              "items": {
                "type": "string"
              },
              "example": [
                "booking",
                "update"
              ]
            }
          }
        }
      }
    },
    "/financial-accounting/financial-booking-log/{cr-reference-id}/{behavior-qualifier}": {
      "get": {
        "tags": [
          "retrieve"
        ],
        "summary": "Retrieve Behavior Qualifier Reference Ids of a given behavior qualifier",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "cr-reference-id",
            "in": "path",
            "description": "Subledger Reference",
            "required": true,
            "type": "string"
          },
          {
            "name": "behavior-qualifier",
            "in": "path",
            "description": "Behavior Qualifier name (ex. booking)",
            "required": true,
            "type": "string"
          },
          {
            "name": "collection-filter",
            "in": "query",
            "description": "Filter to refine result set. ex- 'bookingValueDate < 2016-09-01'",
            "required": false,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Successfully retrieved Behavior Qualifier reference IDs",
            "schema": {
              "type": "array",
              "items": {
                "type": "string"
              },
              "example": [
                "BOOK142",
                "BOOK789",
                "BOOK342"
              ]
            }
          }
        }
      }
    },
    "/financial-accounting/financial-booking-log/{cr-reference-id}": {
      "get": {
        "tags": [
          "retrieve"
        ],
        "summary": "Retrieve sub-ledger record extract/report",
        "operationId": "retrieveFinancialBookingLog",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "cr-reference-id",
            "in": "path",
            "description": "Subledger Reference",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Successfully retrieved Financial Account Subledger",
            "schema": {
              "type": "object",
              "properties": {
                "subledgerReference": {
                  "type": "string",
                  "example": "SR1234",
                  "description": "`status: Not Mapped`\ncore-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier\ngeneral-info: the reference ID to this Financial Booking Log\n"
                },
                "subledgerType": {
                  "type": "string",
                  "example": "accounts receivable",
                  "description": "`status: Not Mapped`\ncore-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text\n"
                },
                "productInstanceReference": {
                  "type": "string",
                  "example": "PI89374",
                  "description": "`status: Not Mapped`\ncore-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier\ngeneral-info: linked product/service reference number\n"
                },
                "businessUnitReference": {
                  "type": "string",
                  "example": "BU89237",
                  "description": "`status: Not Mapped`\ncore-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier\ngeneral-info: link business unit/activity\n"
                },
                "baseCurrency": {
                  "type": "string",
                  "pattern": "^[A-Z]{3,3}$",
                  "description": "`status: Registered`\niso-link: [click_here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/codesets/_bUhmRdp-Ed-ak6NoX_4Aeg_-1745414039)\ngeneral-info: 'Code allocated to a currency, by a maintenance agency, under an international identification scheme as described in the latest edition of the international standard ISO 4217 \"Codes for the representation of currencies and funds\". Valid currency codes are registered with the ISO 4217 Maintenance Agency, and consist of three contiguous letters.'\n",
                  "example": "USD"
                },
                "chartOfAccountBookingRules": {
                  "type": "object",
                  "description": "`status: Not Mapped`\ncore-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary\ngeneral-info: Chart of Account/Booking Rules\n",
                  "properties": {}
                },
                "status": {
                  "type": "string",
                  "example": "active",
                  "description": "`status: Not Mapped`\ncore-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text\n"
                }
              },
              "example": {
                "subledgerType": "accounts receivable",
                "productInstanceReference": "PI89374",
                "subledgerReference": "SR1234",
                "chartOfAccountBookingRules": "{}",
                "businessUnitReference": "BU89237",
                "baseCurrency": "USD",
                "status": "active"
              }
            }
          }
        }
      }
    },
    "/financial-accounting/financial-booking-log/{cr-reference-id}/reporting/{bq-reference-id}": {
      "get": {
        "tags": [
          "retrieve"
        ],
        "summary": "Retrieve sub-ledger record reporting",
        "operationId": "retrieveFinancialBookingLogReporting",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "cr-reference-id",
            "in": "path",
            "description": "Subledger Reference",
            "required": true,
            "type": "string"
          },
          {
            "name": "bq-reference-id",
            "in": "path",
            "description": "Reporting Service Reference",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Successfully retrieved Financial Account Subledger Booking entry",
            "schema": {
              "type": "object",
              "properties": {
                "financialLedgerServiceReference": {
                  "type": "string",
                  "example": "FLSR234",
                  "description": "`status: Not Mapped`\ncore-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier\ngeneral-info: SDR Reference ID\n"
                },
                "subledgerReference": {
                  "type": "string",
                  "example": "SR1234",
                  "description": "`status: Not Mapped`\ncore-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier\ngeneral-info: the reference ID to the Financial Booking Log\n"
                },
                "reportingServiceReference": {
                  "type": "string",
                  "example": "REP234",
                  "description": "`status: Not Mapped`\ncore-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier\ngeneral-info: the reference ID to the reporting service\n"
                },
                "ledgerReportType": {
                  "type": "string",
                  "example": "general",
                  "description": "`status: Not Mapped`\ncore-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text\n"
                },
                "reportingPeriod": {
                  "type": "object",
                  "properties": {
                    "fromDate": {
                      "type": "string",
                      "example": "09-01-2018 07:30:00 EST",
                      "description": "`status: Not Mapped`\ncore-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::DateTime\n"
                    },
                    "toDate": {
                      "type": "string",
                      "example": "09-02-2018 19:30:00 EST",
                      "description": "`status: Not Mapped`\ncore-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::DateTime\n"
                    }
                  },
                  "description": "Specifies a time period with a From DateTime and To DateTime",
                  "example": {
                    "fromDate": "09-01-2018 07:30:00 EST",
                    "toDate": "09-02-2018 19:30:00 EST"
                  }
                },
                "report": {
                  "type": "object",
                  "description": "`status: Not Mapped`\ncore-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary\ngeneral-info: ledger statement\n",
                  "properties": {}
                },
                "reportingResult": {
                  "type": "string",
                  "example": "success",
                  "description": "`status: Not Mapped`\ncore-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Indicator\n"
                }
              },
              "example": {
                "reportingServiceReference": "REP234",
                "financialLedgerServiceReference": "FLSR234",
                "ledgerReportType": "general",
                "reportingPeriod": {
                  "fromDate": "09-01-2018 07:30:00 EST",
                  "toDate": "09-02-2018 19:30:00 EST"
                },
                "subledgerReference": "SR1234",
                "report": "{}",
                "reportingResult": "success"
              }
            }
          }
        }
      }
    },
    "/financial-accounting/financial-booking-log/{cr-reference-id}/bookings/{bq-reference-id}": {
      "get": {
        "tags": [
          "retrieve"
        ],
        "summary": "Retrieve sub-ledger record booking entry",
        "operationId": "retrieveFinancialBookingLogBooking",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "cr-reference-id",
            "in": "path",
            "description": "Subledger Reference",
            "required": true,
            "type": "string"
          },
          {
            "name": "bq-reference-id",
            "in": "path",
            "description": "Booking Reference",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Successfully retrieved Financial Account Subledger Booking entry",
            "schema": {
              "type": "object",
              "properties": {
                "bookingReference": {
                  "type": "string",
                  "example": "BR7237",
                  "description": "`status: Not Mapped`\ncore-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier\ngeneral-info: the reference ID to this Booking/Posting to the ledger\n"
                },
                "subledgerReference": {
                  "type": "string",
                  "example": "SR1234",
                  "description": "`status: Not Mapped`\ncore-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier\ngeneral-info: the reference ID to the Financial Booking Log\n"
                },
                "bookingPurpose": {
                  "type": "string",
                  "description": "`status: Not Mapped`\ncore-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text\n"
                },
                "bookingAmount": {
                  "type": "object",
                  "description": "`status: Not Mapped`\ncore-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Amount\ngeneral-info: credit/debit pair\n",
                  "properties": {}
                },
                "bookingValueDate": {
                  "type": "string",
                  "pattern": "^(?:[1-9]\\d{3}-(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|1\\d|2[0-8])|(?:0[13-9]|1[0-2])-(?:29|30)|(?:0[13578]|1[02])-31)|(?:[1-9]\\d(?:0[48]|[2468][048]|[13579][26])|(?:[2468][048]|[13579][26])00)-02-29)T(?:[01]\\d|2[0-3]):[0-5]\\d:[0-5]\\d(?:\\.[0-9]+)?(?:Z|[+-][01]\\d:[0-5]\\d)?$",
                  "description": "`status: Registered`,\niso-link: [click_here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/datatypes/_YW1tKtp-Ed-ak6NoX_4Aeg_-1624336183)\ngeneral-info: A particular point in the progression of time defined by a mandatory date and a mandatory time component, expressed in either UTC time format (YYYY-MM-DDThh:mm:ss.sssZ), local time with UTC offset format (YYYY-MM-DDThh:mm:ss.sss+/-hh:mm), or local time format (YYYY-MM-DDThh:mm:ss.sss). These representations are defined in \"XML Schema Part 2: Datatypes Second Edition - W3C Recommendation 28 October 2004\" which is aligned with ISO 8601.\nNote on the time format:\n1) beginning / end of calendar day\n00:00:00 = the beginning of a calendar day\n24:00:00 = the end of a calendar day\n2) fractions of second in time format\nDecimal fractions of seconds may be included. In this case, the involved parties shall agree on the maximum number of digits that are allowed.\n",
                  "example": "2018-09-26T05:56:05.007"
                },
                "bookingResult": {
                  "type": "string",
                  "example": "booked",
                  "description": "`status: Not Mapped`\ncore-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Indicator\n"
                }
              },
              "example": {
                "bookingReference": "BR7237",
                "bookingResult": "booked",
                "subledgerReference": "SR1234",
                "bookingValueDate": "2018-09-26T05:56:05.007",
                "bookingPurpose": "bookingPurpose",
                "bookingAmount": "{}"
              }
            }
          }
        }
      }
    },
    "/financial-accounting/financial-booking-log/{cr-reference-id}/updates/{bq-reference-id}": {
      "get": {
        "tags": [
          "retrieve"
        ],
        "summary": "Retrieve sub-ledger update record",
        "operationId": "retrieveFinancialBookingLogUpdate",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "cr-reference-id",
            "in": "path",
            "description": "Subledger Reference",
            "required": true,
            "type": "string"
          },
          {
            "name": "bq-reference-id",
            "in": "path",
            "description": "Update Reference",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Successfully retrieved Financial Account Subledger Update record",
            "schema": {
              "type": "object",
              "properties": {
                "updateReference": {
                  "type": "string",
                  "example": "U2394",
                  "description": "`status: Not Mapped`\ncore-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier\ngeneral-info: the reference ID to this update to the ledger\n"
                },
                "subledgerReference": {
                  "type": "string",
                  "example": "SR1234",
                  "description": "`status: Not Mapped`\ncore-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier\ngeneral-info: the reference ID to the Financial Booking Log\n"
                },
                "ledgerUpdatePurpose": {
                  "type": "string",
                  "example": "current account update",
                  "description": "`status: Not Mapped`\ncore-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text\n"
                },
                "ledgerUpdateEmployeeReference": {
                  "type": "string",
                  "example": "ER123",
                  "description": "`status: Not Mapped`\ncore-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier\ngeneral-info: Employee reference ID, for audit purposes\n"
                },
                "ledgerUpdateDescription": {
                  "type": "string",
                  "example": "Financial log - current account update",
                  "description": "`status: Not Mapped`\ncore-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text\n"
                },
                "ledgerUpdateResult": {
                  "type": "string",
                  "example": "successful",
                  "description": "`status: Not Mapped`\ncore-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Indicator\n"
                }
              },
              "example": {
                "ledgerUpdatePurpose": "current account update",
                "subledgerReference": "SR1234",
                "updateReference": "U2394",
                "ledgerUpdateEmployeeReference": "ER123",
                "ledgerUpdateResult": "successful",
                "ledgerUpdateDescription": "Financial log - current account update"
              }
            }
          }
        }
      }
    },
    "/financial-accounting/financial-booking-log/{cr-reference-id}/updates/{bq-reference-id}/updation": {
      "put": {
        "tags": [
          "update"
        ],
        "summary": "Update/correct details of sub-ledger posting",
        "operationId": "updateFinancialBookingLog",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "cr-reference-id",
            "in": "path",
            "description": "Subledger Reference",
            "required": true,
            "type": "string"
          },
          {
            "name": "bq-reference-id",
            "in": "path",
            "description": "Update Reference",
            "required": true,
            "type": "string"
          },
          {
            "in": "body",
            "name": "body",
            "description": "Update subledger details request payload",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "ledgerUpdatePurpose": {
                  "type": "string",
                  "example": "current account update",
                  "description": "`status: Not Mapped`\ncore-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text\n"
                },
                "ledgerUpdateEmployeeReference": {
                  "type": "string",
                  "example": "ER123",
                  "description": "`status: Not Mapped`\ncore-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier\ngeneral-info: Employee reference ID, for audit purposes\n"
                },
                "ledgerUpdateDescription": {
                  "type": "string",
                  "example": "Financial log - current account update",
                  "description": "`status: Not Mapped`\ncore-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text\n"
                }
              },
              "example": {
                "ledgerUpdatePurpose": "current account update",
                "ledgerUpdateEmployeeReference": "ER123",
                "ledgerUpdateDescription": "Financial log - current account update"
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "updated Financial Accounting record successfully",
            "schema": {
              "type": "object",
              "properties": {
                "updateReference": {
                  "type": "string",
                  "example": "U2394",
                  "description": "`status: Not Mapped`\ncore-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier\ngeneral-info: the reference ID to this update to the ledger\n"
                },
                "subledgerReference": {
                  "type": "string",
                  "example": "SR1234",
                  "description": "`status: Not Mapped`\ncore-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier\ngeneral-info: the reference ID to the Financial Booking Log\n"
                },
                "ledgerUpdatePurpose": {
                  "type": "string",
                  "example": "current account update",
                  "description": "`status: Not Mapped`\ncore-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text\n"
                },
                "ledgerUpdateEmployeeReference": {
                  "type": "string",
                  "example": "ER123",
                  "description": "`status: Not Mapped`\ncore-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier\ngeneral-info: Employee reference ID, for audit purposes\n"
                },
                "ledgerUpdateDescription": {
                  "type": "string",
                  "example": "Financial log - current account update",
                  "description": "`status: Not Mapped`\ncore-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text\n"
                },
                "ledgerUpdateResult": {
                  "type": "string",
                  "example": "successful",
                  "description": "`status: Not Mapped`\ncore-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Indicator\n"
                }
              },
              "example": {
                "ledgerUpdatePurpose": "current account update",
                "subledgerReference": "SR1234",
                "updateReference": "U2394",
                "ledgerUpdateEmployeeReference": "ER123",
                "ledgerUpdateResult": "successful",
                "ledgerUpdateDescription": "Financial log - current account update"
              }
            }
          }
        }
      }
    },
    "/financial-accounting/financial-booking-log/{cr-reference-id}/bookings/recording": {
      "post": {
        "tags": [
          "record"
        ],
        "summary": "Record a sub-ledger entry (includes classification)",
        "operationId": "recordFinancialBookingLog",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "cr-reference-id",
            "in": "path",
            "description": "Subledger Reference",
            "required": true,
            "type": "string"
          },
          {
            "in": "body",
            "name": "body",
            "description": "Record subledger entry request payload",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "bookingPurpose": {
                  "type": "string",
                  "description": "`status: Not Mapped`\ncore-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text\n"
                },
                "bookingAmount": {
                  "type": "object",
                  "description": "`status: Not Mapped`\ncore-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Amount\ngeneral-info: credit/debit pair\n",
                  "properties": {}
                },
                "bookingValueDate": {
                  "type": "string",
                  "pattern": "^(?:[1-9]\\d{3}-(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|1\\d|2[0-8])|(?:0[13-9]|1[0-2])-(?:29|30)|(?:0[13578]|1[02])-31)|(?:[1-9]\\d(?:0[48]|[2468][048]|[13579][26])|(?:[2468][048]|[13579][26])00)-02-29)T(?:[01]\\d|2[0-3]):[0-5]\\d:[0-5]\\d(?:\\.[0-9]+)?(?:Z|[+-][01]\\d:[0-5]\\d)?$",
                  "description": "`status: Registered`,\niso-link: [click_here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/datatypes/_YW1tKtp-Ed-ak6NoX_4Aeg_-1624336183)\ngeneral-info: A particular point in the progression of time defined by a mandatory date and a mandatory time component, expressed in either UTC time format (YYYY-MM-DDThh:mm:ss.sssZ), local time with UTC offset format (YYYY-MM-DDThh:mm:ss.sss+/-hh:mm), or local time format (YYYY-MM-DDThh:mm:ss.sss). These representations are defined in \"XML Schema Part 2: Datatypes Second Edition - W3C Recommendation 28 October 2004\" which is aligned with ISO 8601.\nNote on the time format:\n1) beginning / end of calendar day\n00:00:00 = the beginning of a calendar day\n24:00:00 = the end of a calendar day\n2) fractions of second in time format\nDecimal fractions of seconds may be included. In this case, the involved parties shall agree on the maximum number of digits that are allowed.\n",
                  "example": "2018-09-26T05:56:05.007"
                },
                "bookingResult": {
                  "type": "object",
                  "description": "`status: Not Mapped`\ncore-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Indicator\n",
                  "properties": {}
                }
              },
              "example": {
                "bookingResult": "{}",
                "bookingValueDate": "2018-09-26T05:56:05.007",
                "bookingPurpose": "bookingPurpose",
                "bookingAmount": "{}"
              }
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created a Financial Accounting record successfully",
            "schema": {
              "type": "object",
              "properties": {
                "recordingRecordReference": {
                  "type": "string",
                  "example": "RRR4678",
                  "description": "`status: Not Mapped`\ncore-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier\n"
                },
                "recordingRecordStatus": {
                  "type": "string",
                  "example": "Applied",
                  "description": "`status: Not Mapped`\ncore-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text\n"
                }
              },
              "example": {
                "recordingRecordReference": "RRR4678",
                "recordingRecordStatus": "Applied"
              }
            }
          }
        }
      }
    }
  },
  "definitions": {
    "RetrieveFinancialBookingLogResponse": {
      "type": "object",
      "properties": {
        "subledgerReference": {
          "type": "string",
          "example": "SR1234",
          "description": "`status: Not Mapped`\ncore-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier\ngeneral-info: the reference ID to this Financial Booking Log\n"
        },
        "subledgerType": {
          "type": "string",
          "example": "accounts receivable",
          "description": "`status: Not Mapped`\ncore-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text\n"
        },
        "productInstanceReference": {
          "type": "string",
          "example": "PI89374",
          "description": "`status: Not Mapped`\ncore-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier\ngeneral-info: linked product/service reference number\n"
        },
        "businessUnitReference": {
          "type": "string",
          "example": "BU89237",
          "description": "`status: Not Mapped`\ncore-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier\ngeneral-info: link business unit/activity\n"
        },
        "baseCurrency": {
          "type": "string",
          "pattern": "^[A-Z]{3,3}$",
          "description": "`status: Registered`\niso-link: [click_here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/codesets/_bUhmRdp-Ed-ak6NoX_4Aeg_-1745414039)\ngeneral-info: 'Code allocated to a currency, by a maintenance agency, under an international identification scheme as described in the latest edition of the international standard ISO 4217 \"Codes for the representation of currencies and funds\". Valid currency codes are registered with the ISO 4217 Maintenance Agency, and consist of three contiguous letters.'\n",
          "example": "USD"
        },
        "chartOfAccountBookingRules": {
          "type": "object",
          "description": "`status: Not Mapped`\ncore-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary\ngeneral-info: Chart of Account/Booking Rules\n",
          "properties": {}
        },
        "status": {
          "type": "string",
          "example": "active",
          "description": "`status: Not Mapped`\ncore-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text\n"
        }
      },
      "example": {
        "subledgerType": "accounts receivable",
        "productInstanceReference": "PI89374",
        "subledgerReference": "SR1234",
        "chartOfAccountBookingRules": "{}",
        "businessUnitReference": "BU89237",
        "baseCurrency": "USD",
        "status": "active"
      }
    },
    "ReportingBaseWithIdAndRoot": {
      "type": "object",
      "properties": {
        "financialLedgerServiceReference": {
          "type": "string",
          "example": "FLSR234",
          "description": "`status: Not Mapped`\ncore-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier\ngeneral-info: SDR Reference ID\n"
        },
        "subledgerReference": {
          "type": "string",
          "example": "SR1234",
          "description": "`status: Not Mapped`\ncore-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier\ngeneral-info: the reference ID to the Financial Booking Log\n"
        },
        "reportingServiceReference": {
          "type": "string",
          "example": "REP234",
          "description": "`status: Not Mapped`\ncore-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier\ngeneral-info: the reference ID to the reporting service\n"
        },
        "ledgerReportType": {
          "type": "string",
          "example": "general",
          "description": "`status: Not Mapped`\ncore-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text\n"
        },
        "reportingPeriod": {
          "type": "object",
          "properties": {
            "fromDate": {
              "type": "string",
              "example": "09-01-2018 07:30:00 EST",
              "description": "`status: Not Mapped`\ncore-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::DateTime\n"
            },
            "toDate": {
              "type": "string",
              "example": "09-02-2018 19:30:00 EST",
              "description": "`status: Not Mapped`\ncore-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::DateTime\n"
            }
          },
          "description": "Specifies a time period with a From DateTime and To DateTime",
          "example": {
            "fromDate": "09-01-2018 07:30:00 EST",
            "toDate": "09-02-2018 19:30:00 EST"
          }
        },
        "report": {
          "type": "object",
          "description": "`status: Not Mapped`\ncore-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary\ngeneral-info: ledger statement\n",
          "properties": {}
        },
        "reportingResult": {
          "type": "string",
          "example": "success",
          "description": "`status: Not Mapped`\ncore-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Indicator\n"
        }
      },
      "example": {
        "reportingServiceReference": "REP234",
        "financialLedgerServiceReference": "FLSR234",
        "ledgerReportType": "general",
        "reportingPeriod": {
          "fromDate": "09-01-2018 07:30:00 EST",
          "toDate": "09-02-2018 19:30:00 EST"
        },
        "subledgerReference": "SR1234",
        "report": "{}",
        "reportingResult": "success"
      }
    },
    "BookingBase": {
      "type": "object",
      "properties": {
        "bookingPurpose": {
          "type": "string",
          "description": "`status: Not Mapped`\ncore-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text\n"
        },
        "bookingAmount": {
          "type": "object",
          "description": "`status: Not Mapped`\ncore-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Amount\ngeneral-info: credit/debit pair\n",
          "properties": {}
        },
        "bookingValueDate": {
          "type": "string",
          "pattern": "^(?:[1-9]\\d{3}-(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|1\\d|2[0-8])|(?:0[13-9]|1[0-2])-(?:29|30)|(?:0[13578]|1[02])-31)|(?:[1-9]\\d(?:0[48]|[2468][048]|[13579][26])|(?:[2468][048]|[13579][26])00)-02-29)T(?:[01]\\d|2[0-3]):[0-5]\\d:[0-5]\\d(?:\\.[0-9]+)?(?:Z|[+-][01]\\d:[0-5]\\d)?$",
          "description": "`status: Registered`,\niso-link: [click_here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/datatypes/_YW1tKtp-Ed-ak6NoX_4Aeg_-1624336183)\ngeneral-info: A particular point in the progression of time defined by a mandatory date and a mandatory time component, expressed in either UTC time format (YYYY-MM-DDThh:mm:ss.sssZ), local time with UTC offset format (YYYY-MM-DDThh:mm:ss.sss+/-hh:mm), or local time format (YYYY-MM-DDThh:mm:ss.sss). These representations are defined in \"XML Schema Part 2: Datatypes Second Edition - W3C Recommendation 28 October 2004\" which is aligned with ISO 8601.\nNote on the time format:\n1) beginning / end of calendar day\n00:00:00 = the beginning of a calendar day\n24:00:00 = the end of a calendar day\n2) fractions of second in time format\nDecimal fractions of seconds may be included. In this case, the involved parties shall agree on the maximum number of digits that are allowed.\n",
          "example": "2018-09-26T05:56:05.007"
        },
        "bookingResult": {
          "type": "object",
          "description": "`status: Not Mapped`\ncore-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Indicator\n",
          "properties": {}
        }
      },
      "example": {
        "bookingResult": "{}",
        "bookingValueDate": "2018-09-26T05:56:05.007",
        "bookingPurpose": "bookingPurpose",
        "bookingAmount": "{}"
      }
    },
    "BookingBaseWithIdAndRoot": {
      "type": "object",
      "properties": {
        "bookingReference": {
          "type": "string",
          "example": "BR7237",
          "description": "`status: Not Mapped`\ncore-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier\ngeneral-info: the reference ID to this Booking/Posting to the ledger\n"
        },
        "subledgerReference": {
          "type": "string",
          "example": "SR1234",
          "description": "`status: Not Mapped`\ncore-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier\ngeneral-info: the reference ID to the Financial Booking Log\n"
        },
        "bookingPurpose": {
          "type": "string",
          "description": "`status: Not Mapped`\ncore-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text\n"
        },
        "bookingAmount": {
          "type": "object",
          "description": "`status: Not Mapped`\ncore-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Amount\ngeneral-info: credit/debit pair\n",
          "properties": {}
        },
        "bookingValueDate": {
          "type": "string",
          "pattern": "^(?:[1-9]\\d{3}-(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|1\\d|2[0-8])|(?:0[13-9]|1[0-2])-(?:29|30)|(?:0[13578]|1[02])-31)|(?:[1-9]\\d(?:0[48]|[2468][048]|[13579][26])|(?:[2468][048]|[13579][26])00)-02-29)T(?:[01]\\d|2[0-3]):[0-5]\\d:[0-5]\\d(?:\\.[0-9]+)?(?:Z|[+-][01]\\d:[0-5]\\d)?$",
          "description": "`status: Registered`,\niso-link: [click_here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/datatypes/_YW1tKtp-Ed-ak6NoX_4Aeg_-1624336183)\ngeneral-info: A particular point in the progression of time defined by a mandatory date and a mandatory time component, expressed in either UTC time format (YYYY-MM-DDThh:mm:ss.sssZ), local time with UTC offset format (YYYY-MM-DDThh:mm:ss.sss+/-hh:mm), or local time format (YYYY-MM-DDThh:mm:ss.sss). These representations are defined in \"XML Schema Part 2: Datatypes Second Edition - W3C Recommendation 28 October 2004\" which is aligned with ISO 8601.\nNote on the time format:\n1) beginning / end of calendar day\n00:00:00 = the beginning of a calendar day\n24:00:00 = the end of a calendar day\n2) fractions of second in time format\nDecimal fractions of seconds may be included. In this case, the involved parties shall agree on the maximum number of digits that are allowed.\n",
          "example": "2018-09-26T05:56:05.007"
        },
        "bookingResult": {
          "type": "string",
          "example": "booked",
          "description": "`status: Not Mapped`\ncore-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Indicator\n"
        }
      },
      "example": {
        "bookingReference": "BR7237",
        "bookingResult": "booked",
        "subledgerReference": "SR1234",
        "bookingValueDate": "2018-09-26T05:56:05.007",
        "bookingPurpose": "bookingPurpose",
        "bookingAmount": "{}"
      }
    },
    "UpdateBase": {
      "type": "object",
      "properties": {
        "ledgerUpdatePurpose": {
          "type": "string",
          "example": "current account update",
          "description": "`status: Not Mapped`\ncore-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text\n"
        },
        "ledgerUpdateEmployeeReference": {
          "type": "string",
          "example": "ER123",
          "description": "`status: Not Mapped`\ncore-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier\ngeneral-info: Employee reference ID, for audit purposes\n"
        },
        "ledgerUpdateDescription": {
          "type": "string",
          "example": "Financial log - current account update",
          "description": "`status: Not Mapped`\ncore-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text\n"
        }
      },
      "example": {
        "ledgerUpdatePurpose": "current account update",
        "ledgerUpdateEmployeeReference": "ER123",
        "ledgerUpdateDescription": "Financial log - current account update"
      }
    },
    "UpdateBaseWithIdAndRoot": {
      "type": "object",
      "properties": {
        "updateReference": {
          "type": "string",
          "example": "U2394",
          "description": "`status: Not Mapped`\ncore-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier\ngeneral-info: the reference ID to this update to the ledger\n"
        },
        "subledgerReference": {
          "type": "string",
          "example": "SR1234",
          "description": "`status: Not Mapped`\ncore-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier\ngeneral-info: the reference ID to the Financial Booking Log\n"
        },
        "ledgerUpdatePurpose": {
          "type": "string",
          "example": "current account update",
          "description": "`status: Not Mapped`\ncore-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text\n"
        },
        "ledgerUpdateEmployeeReference": {
          "type": "string",
          "example": "ER123",
          "description": "`status: Not Mapped`\ncore-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier\ngeneral-info: Employee reference ID, for audit purposes\n"
        },
        "ledgerUpdateDescription": {
          "type": "string",
          "example": "Financial log - current account update",
          "description": "`status: Not Mapped`\ncore-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text\n"
        },
        "ledgerUpdateResult": {
          "type": "string",
          "example": "successful",
          "description": "`status: Not Mapped`\ncore-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Indicator\n"
        }
      },
      "example": {
        "ledgerUpdatePurpose": "current account update",
        "subledgerReference": "SR1234",
        "updateReference": "U2394",
        "ledgerUpdateEmployeeReference": "ER123",
        "ledgerUpdateResult": "successful",
        "ledgerUpdateDescription": "Financial log - current account update"
      }
    },
    "RecordFinancialAccountResponse": {
      "type": "object",
      "properties": {
        "recordingRecordReference": {
          "type": "string",
          "example": "RRR4678",
          "description": "`status: Not Mapped`\ncore-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier\n"
        },
        "recordingRecordStatus": {
          "type": "string",
          "example": "Applied",
          "description": "`status: Not Mapped`\ncore-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text\n"
        }
      },
      "example": {
        "recordingRecordReference": "RRR4678",
        "recordingRecordStatus": "Applied"
      }
    },
    "CurrencyCode": {
      "type": "string",
      "pattern": "^[A-Z]{3,3}$",
      "description": "`status: Registered`\niso-link: [click_here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/codesets/_bUhmRdp-Ed-ak6NoX_4Aeg_-1745414039)\ngeneral-info: 'Code allocated to a currency, by a maintenance agency, under an international identification scheme as described in the latest edition of the international standard ISO 4217 \"Codes for the representation of currencies and funds\". Valid currency codes are registered with the ISO 4217 Maintenance Agency, and consist of three contiguous letters.'\n",
      "example": "USD"
    },
    "DateTimePeriod": {
      "type": "object",
      "properties": {
        "fromDate": {
          "type": "string",
          "example": "09-01-2018 07:30:00 EST",
          "description": "`status: Not Mapped`\ncore-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::DateTime\n"
        },
        "toDate": {
          "type": "string",
          "example": "09-02-2018 19:30:00 EST",
          "description": "`status: Not Mapped`\ncore-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::DateTime\n"
        }
      },
      "description": "Specifies a time period with a From DateTime and To DateTime",
      "example": {
        "fromDate": "09-01-2018 07:30:00 EST",
        "toDate": "09-02-2018 19:30:00 EST"
      }
    },
    "ISODateTime": {
      "type": "string",
      "pattern": "^(?:[1-9]\\d{3}-(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|1\\d|2[0-8])|(?:0[13-9]|1[0-2])-(?:29|30)|(?:0[13578]|1[02])-31)|(?:[1-9]\\d(?:0[48]|[2468][048]|[13579][26])|(?:[2468][048]|[13579][26])00)-02-29)T(?:[01]\\d|2[0-3]):[0-5]\\d:[0-5]\\d(?:\\.[0-9]+)?(?:Z|[+-][01]\\d:[0-5]\\d)?$",
      "description": "`status: Registered`,\niso-link: [click_here](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/datatypes/_YW1tKtp-Ed-ak6NoX_4Aeg_-1624336183)\ngeneral-info: A particular point in the progression of time defined by a mandatory date and a mandatory time component, expressed in either UTC time format (YYYY-MM-DDThh:mm:ss.sssZ), local time with UTC offset format (YYYY-MM-DDThh:mm:ss.sss+/-hh:mm), or local time format (YYYY-MM-DDThh:mm:ss.sss). These representations are defined in \"XML Schema Part 2: Datatypes Second Edition - W3C Recommendation 28 October 2004\" which is aligned with ISO 8601.\nNote on the time format:\n1) beginning / end of calendar day\n00:00:00 = the beginning of a calendar day\n24:00:00 = the end of a calendar day\n2) fractions of second in time format\nDecimal fractions of seconds may be included. In this case, the involved parties shall agree on the maximum number of digits that are allowed.\n",
      "example": "2018-09-26T05:56:05.007"
    }
  }
}